---
title: "viz_part1"
author: "Luan Mengxiao"
date: "2023-09-28"
output: github_document
---

```{r setup}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Get the data ro be visualized from the Internet.

```{r data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Let's make a plot.

```{r plot1}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

pipes and stuff

```{r plot2}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggplot_nyc_weather = 
  weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggplot_nyc_weather
```

## Fancy plot

```{r plot3}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth()

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth()

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_smooth()

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE)

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3) +
  geom_smooth(se = FALSE)
```

Plot with facets

```{r plot4}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  geom_smooth() + 
  facet_grid(. ~ name)

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  geom_smooth() + 
  facet_grid(name ~ .)
```

Let's try a different plot.

```{r plot5}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .3) + 
  geom_smooth() + 
  facet_grid(. ~ name)
```

try assigning a specific color

```{r plot6}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = date, y = tmax)) + 
  geom_point(color = "blue")

weather_df |>
  filter(name != "CentralPark_NY") |>
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .7, size = .5)
```

```{r plot7}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

weather_df |>
  filter(name == "Molokai_HI") |>
  ggplot(aes(x = date, y = tmax)) + 
  geom_line(alpha = .5) + 
  geom_point(size = .5)
```

## univariate plotting

histogram

```{r plot8}
ggplot(weather_df, aes(x = tmax)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge")
```

density plot

```{r plot9}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3, adjust = 2)
```

using boxlots

```{r plot10}
ggplot(weather_df, aes(y = tmax, x = name)) + 
  geom_boxplot()
```

violin plots

```{r plot11}
ggplot(weather_df, aes(y = tmax, x = name)) + 
  geom_violin()
```

ridge plot

```{r plot12}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges()
```

## saving and embedding plots

```{r save}
ggplot_weather = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggplot_weather

ggsave("results/ggplot_weather.pdf", ggplot_weather)
```

```{r, fig.width = 6, fig.asp = .6}
ggplot_weather
```